### ISSUE TITLE
make quick start for uninitiated user

### ISSUE THREAD

**Issue by cbird808** [cbirdlab/charybdis#1]

**Comment by ekrell** [comment]
Done

**Comment by ekrell** [comment]
You will see a quickstart in the README, but this is a work-in-progress.

**Comment by ekrell** [comment]
There is now a completed Quick Start guide in the README. 
I was able to get it to work, but I made the guide while trying to get it to run on a fresh machine.
So it would be best if someone else is able to replicate the result before I close the issue.

**Comment by ekrell** [comment]
Well, I was able to recreate everything by blindly following the steps so I think it is safe to close.
