### ISSUE TITLE
filtering junk out of blastdb

### ISSUE THREAD

**Issue by cbird808** [cbirdlab/charybdis#27]
I want to review what is being filtered from the blastdb by the list of gi's to ignore. Putting this here to remind me

Here's an email from Jason to check against:
From: Selwyn, Jason <jselwyn@islander.tamucc.edu>
Sent: Tuesday, August 13, 2019 9:36:16 AM
To: Bird, Chris <Chris.Bird@tamucc.edu>; Krell, Evan <evan.krell@tamucc.edu>
Subject: RE: crittersVStubes.R 
 
What I used that was relatively effective was as part of an R pipe do this:

the_data %>%
  mutate(species=if_else(str_count(species,' ')>1,'FAKE_SPECIES',species)) %>%
  mutate(species=if_else(str_detect(species,'sp\\.'),'FAKE_SPECIES',species)) %>% 
  mutate(species=ifelse(species=='FAKE_SPECIES',NA,species)) %>% 

To get rid of any species that has more than one “space” in the name and to get rid of any that has “sp.” In the name.

I had thought the reason we are rerunning everything is because we culled the actual database to remove those items?

Jason

**Comment by cbird808** [comment]
ok, so I looked into this further and I don't think we are creating a list of gi to ignore based upon "environmental" "spp" etc.   it would be nice to have the script that we use to create this gi list so that it cant be updated easily

**Comment by ekrell** [comment]
I'll just repeat a bit of the email discussion so I can close this with explanation.

We use NCBI's **eutils** to get a list of GIs based on a number of search terms. 
This is done with script **bin/Get_env_gi_list.sh**. 
It currently has 'sp' as one of the terms and will soon be expanded to have 'spp' as well. 

An obvious extension would allow the user to provide a custom string of search terms to replace the default set.
