### ISSUE TITLE
BOLD taxonmy throws error in crittersVtubes.R

### ISSUE THREAD

**Issue by cbird808** [cbirdlab/charybdis#28]
`Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) : `
`  Timeout was reached: Connection timed out after 10000 milliseconds`

I take this to mean that it's not filling in the holes left by the ncbi database

**Comment by ekrell** [comment]
Unfortunately this is sensitive to the health of the BOLD database at the time of the run. 
At one point, the inability to connect was killing the run entirely. I can't remember if I ended up using a try/catch to make sure that it would at least finish the run. Either way, we don't want to be dependent on external databases. We have the ability to generate locale BOLD databases. Surely there is a way we can do this on our side.

**Comment by cbird808** [comment]
I just troubleshot the code.  

I think the code is 100% working.  I suspect that we are getting blocked by bold for hitting its db too much.  I make this conclusion because I was just able to run through the whole process successfully.  When I tried again, I made it to the 760th otu.  Now i only get to 3 otu before getting the error

I put an issue on the developer's github: https://github.com/ropensci/bold/issues/68 


`

**Comment by cbird808** [comment]
a potential solution was provided by the author of the function that's causing the error, see link above

**Comment by cbird808** [comment]
i added tryCatch() to prevent pipeline breaking.  it should notify user if the bold website times out

**Comment by cbird808** [comment]
How do we generate or download local BOLD databases?  I did a little bit of searching and only found bold's web page based query
