### ISSUE TITLE
CROP_size_fix.sh commenting correct?

### ISSUE THREAD

**Issue by cbird808** [cbirdlab/charybdis#30]
there are blocks of code commented out in this script.  Should they just be uncommented for a new run??

**Comment by ekrell** [comment]
I don't recall editing that script in a very long time. So I suspect that the commented out chunks are just old, bad code that was replaced but not deleted. In one case, the comment "This builds the table" is used both in the commented-out and the remaining section. If this script runs (and it does so for the test example) then we should be able to remove those sections entirely.
